class FAError(Exception):
    pass


class FAAuth(Exception):
    pass